### ISSUE TITLE
Android: banner truncates in landscape orientation

### ISSUE THREAD

**Issue by alexeyfeskov** [defold/extension-admob#12]
**Describe the bug (REQUIRED)**
Top-positioned banners are truncating in landscape mode on displays with rounded corners (Android 9+ devices : Xiaomi Mi 9 SE and some others)
![image](https://user-images.githubusercontent.com/3815262/129446970-8d5a857c-ffe2-4dae-bcc7-8296bdb6a4c5.png)![image](https://user-images.githubusercontent.com/3815262/129446975-9e55f5cb-0e6e-4d34-bda4-e40f735f32a2.png)

**To Reproduce (REQUIRED)**
1. Download [lasted release](https://github.com/defold/extension-admob/archive/refs/tags/2.0.2.zip) and open with Defold Editor (1.2.185 in my case)
2. Turn on `Dynamic Orientation` in `game.project`
3. Bundle and install APK on affected device
4. Load banner and show at `admod.POS_TOP_CENTER`
5. Observe: in landscape orientation, the banner is truncated

**Expected behavior (REQUIRED)**
Banner is fully visible

**Platforms (REQUIRED):**
 - Android 9+, any device with a rounded-corner display

**Additional context (OPTIONAL):**
I've fix same issue for [Applovin Max](https://github.com/alexeyfeskov/defold-maxsdk/pull/12) and will try to port this fix for AdMob

**Comment by alexeyfeskov** [comment]
I've create PR to fix it. https://github.com/defold/extension-admob/pull/13

**Comment by AGulev** [comment]
Thank you @alexeyfeskov !!!
