### ISSUE TITLE
Extension doesn't work like a library (DEF-2795)

### ISSUE THREAD

**Issue by AGulev** [defold/extension-admob#2]
If I add extension like a dependency - it doesn't work.
Cloud build return error:
No resource found that matches the given name (at 'theme' with value @style.Theme.IAPTheme)

All works fine if add folder admob into project

**Comment by mathiaswking** [comment]
Thanks for reporting! I'll look into this!

**Comment by AGulev** [comment]
it seems like fixed with DEF-2977
