### ISSUE TITLE
Add new type of ADs `Rewarded interstitial`

### ISSUE THREAD

**Issue by AGulev** [defold/extension-admob#22]
https://developers.google.com/admob/android/rewarded-interstitial

**Comment by amel** [comment]
@britzl, if it's not too much trouble, could you also plan this?

**Comment by AGulev** [comment]
Added in [3.4.0](https://github.com/defold/extension-admob/releases/tag/3.4.0)

**Comment by amel** [comment]
Appreciate it @AGulev, thanks!
