### ISSUE TITLE
Ads not displaying.

### ISSUE THREAD

**Issue by Green-Robot-Dev-Studios** [defold/extension-admob#5]
Hello. I am a newbie to defold and trying to set up ads in the app. Here is the code that I am using to load in a banner: 
`admob.load_banner('ca-app-pub-5899340000115/52770000', { width = 320, height = 50 }, callback )`
I added in the callback this line of code:
`admob.show_banner()`
I also added all the requires things in the configs and everything. What am I missing?

**Comment by Green-Robot-Dev-Studios** [comment]
The ad does not show up on a mobile device and I have no way of getting the debug log off it.

**Comment by AGulev** [comment]
[New implementation of AdMob SDK from scratch released](https://github.com/defold/extension-admob/releases/tag/2.0.0)
