### ISSUE TITLE
Not Working - Defold Editor 2 - 1.2.150

### ISSUE THREAD

**Issue by lrxit** [defold/extension-admob#6]
Downloaded sources but,

running with engine on android device:

![Capture](https://user-images.githubusercontent.com/49574732/56071963-8df89e00-5d92-11e9-9ef4-b761e744beee.PNG)

Bundle Android application:

![Capture2](https://user-images.githubusercontent.com/49574732/56072001-ec258100-5d92-11e9-82f9-40396b3291ba.PNG)

**Comment by AGulev** [comment]
[New implementation of AdMob SDK from scratch released](https://github.com/defold/extension-admob/releases/tag/2.0.0)
